# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "digital_ocean"
  config.vm.synced_folder ".", "/vagrant", :nfs => true

  config.vm.provider :digital_ocean do |vm|
  end
end
